package com.myspace.temenosapprovals;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TransactionRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("partyId")
	private java.lang.String partyId;
	@org.kie.api.definition.type.Label("serviceRequestType")
	private java.lang.String serviceRequestType;
	@org.kie.api.definition.type.Label("userId")
	private java.lang.String userId;
	@org.kie.api.definition.type.Label("payerAccountId")
	private java.lang.String payerAccountId;
	@org.kie.api.definition.type.Label("payerSortCode")
	private java.lang.String payerSortCode;
	@org.kie.api.definition.type.Label("payeeName")
	private java.lang.String payeeName;
	@org.kie.api.definition.type.Label("payeeAccountNumber")
	private java.lang.String payeeAccountNumber;
	@org.kie.api.definition.type.Label("payeeAccountSortcode")
	private java.lang.String payeeAccountSortcode;
	@org.kie.api.definition.type.Label("transactionNarrative")
	private java.lang.String transactionNarrative;
	@org.kie.api.definition.type.Label("frequency")
	private java.lang.String frequency;
	@org.kie.api.definition.type.Label("validUntil")
	private java.lang.String validUntil;
	@org.kie.api.definition.type.Label("amount")
	private int amount;
	@org.kie.api.definition.type.Label("currency")
	private java.lang.String currency;
	@org.kie.api.definition.type.Label("chargeCode")
	private java.lang.String chargeCode;
	@org.kie.api.definition.type.Label("charges")
	private java.lang.String charges;

	public TransactionRequest() {
	}

	public java.lang.String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(java.lang.String partyId) {
		this.partyId = partyId;
	}

	public java.lang.String getServiceRequestType() {
		return this.serviceRequestType;
	}

	public void setServiceRequestType(java.lang.String serviceRequestType) {
		this.serviceRequestType = serviceRequestType;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.String getPayerAccountId() {
		return this.payerAccountId;
	}

	public void setPayerAccountId(java.lang.String payerAccountId) {
		this.payerAccountId = payerAccountId;
	}

	public java.lang.String getPayerSortCode() {
		return this.payerSortCode;
	}

	public void setPayerSortCode(java.lang.String payerSortCode) {
		this.payerSortCode = payerSortCode;
	}

	public java.lang.String getPayeeName() {
		return this.payeeName;
	}

	public void setPayeeName(java.lang.String payeeName) {
		this.payeeName = payeeName;
	}

	public java.lang.String getPayeeAccountNumber() {
		return this.payeeAccountNumber;
	}

	public void setPayeeAccountNumber(java.lang.String payeeAccountNumber) {
		this.payeeAccountNumber = payeeAccountNumber;
	}

	public java.lang.String getPayeeAccountSortcode() {
		return this.payeeAccountSortcode;
	}

	public void setPayeeAccountSortcode(java.lang.String payeeAccountSortcode) {
		this.payeeAccountSortcode = payeeAccountSortcode;
	}

	public java.lang.String getTransactionNarrative() {
		return this.transactionNarrative;
	}

	public void setTransactionNarrative(java.lang.String transactionNarrative) {
		this.transactionNarrative = transactionNarrative;
	}

	public java.lang.String getFrequency() {
		return this.frequency;
	}

	public void setFrequency(java.lang.String frequency) {
		this.frequency = frequency;
	}

	public java.lang.String getValidUntil() {
		return this.validUntil;
	}

	public void setValidUntil(java.lang.String validUntil) {
		this.validUntil = validUntil;
	}

	public java.lang.String getCurrency() {
		return this.currency;
	}

	public void setCurrency(java.lang.String currency) {
		this.currency = currency;
	}

	public java.lang.String getChargeCode() {
		return this.chargeCode;
	}

	public void setChargeCode(java.lang.String chargeCode) {
		this.chargeCode = chargeCode;
	}

	public java.lang.String getCharges() {
		return this.charges;
	}

	public void setCharges(java.lang.String charges) {
		this.charges = charges;
	}

	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	public TransactionRequest(java.lang.String partyId,
			java.lang.String serviceRequestType, java.lang.String userId,
			java.lang.String payerAccountId, java.lang.String payerSortCode,
			java.lang.String payeeName, java.lang.String payeeAccountNumber,
			java.lang.String payeeAccountSortcode,
			java.lang.String transactionNarrative, java.lang.String frequency,
			java.lang.String validUntil, int amount, java.lang.String currency,
			java.lang.String chargeCode, java.lang.String charges) {
		this.partyId = partyId;
		this.serviceRequestType = serviceRequestType;
		this.userId = userId;
		this.payerAccountId = payerAccountId;
		this.payerSortCode = payerSortCode;
		this.payeeName = payeeName;
		this.payeeAccountNumber = payeeAccountNumber;
		this.payeeAccountSortcode = payeeAccountSortcode;
		this.transactionNarrative = transactionNarrative;
		this.frequency = frequency;
		this.validUntil = validUntil;
		this.amount = amount;
		this.currency = currency;
		this.chargeCode = chargeCode;
		this.charges = charges;
	}

}